CREATE TABLE DUENO(
        DNI integer NOT NULL,
        primary key(DNI),
        NOMBRE VARCHAR(25) NOT NULL,
        APELLIDO VARCHAR(25) NOT NULL,
        TELEFONO INTEGER,
        DIRECCION VARCHAR(100)
);
CREATE TABLE PERRO(
        ID_PERRO INTEGER NOT NULL,
        primary key(ID_PERRO),
        NOMBRE VARCHAR(25) NOT NULL,
        FECHA_NACIMIENTO DATE NOT NULL,
        SEXO CHAR,
        DNI_DUENO INTEGER,
        CONSTRAINT fk_DNI_DUENO
        FOREIGN KEY(DNI_DUENO)
        REFERENCES DUENO(DNI)
);

CREATE TABLE HISTORIAL(
       ID_HISTORIAL INTEGER NOT NULL,
       primary key(ID_HISTORIAL),
       FECHA DATE NOT NULL,
       PERRO INTEGER NOT NULL,
       DESCRIPCION VARCHAR(100) NOT NULL,
       MONTO DECIMAL(10,2) NOT NULL,
       CONSTRAINT fk_PERRO
       FOREIGN KEY(PERRO)
       REFERENCES PERRO(ID_PERRO)
);
INSERT INTO DUENO VALUES
        (25659606, 'PEDRO',  'LOZANO',  1130292055,'PASAJE INMIGRANTE 846');
INSERT INTO PERRO VALUES
        (1, 'VADER',  '2018-03-01',  'M',25659606);
SELECT * FROM DUENO INNER JOIN PERRO ON DUENO.DNI=PERRO.DNI_DUENO WHERE DUENO.NOMBRE="PEDRO"        ;

